/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author Marcelo
 */
public class ViewListarClientes extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private ViewLancarVenda viewLancarVenda;
    
    
    private int linhaSelecionada = -1;
    
    public ViewListarClientes(List<Cliente> clientes, ViewLancarVenda viewLancarVenda) {
        initComponents();
        carregarTabela();
        carregarDados(clientes);
        
        this.viewLancarVenda = viewLancarVenda;
    }
    
     private void carregarTabela() {
        tableModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Id", "Nome", "Telefone", "Email"}){
                    
                    @Override
                    public boolean isCellEditable(int row, int column){
                        return false;
                    }
                };
      
        tbClientes.setModel(tableModel);
        
        tbClientes.getColumnModel()
                .getColumn(0)
                .setPreferredWidth(0);
        
        tbClientes.getColumnModel()
                .getColumn(1)
                .setPreferredWidth(100);
        
        tbClientes.getColumnModel()
                .getColumn(2)
                .setPreferredWidth(30);
        
        tbClientes.getColumnModel()
                .getColumn(3)
                .setPreferredWidth(70);
    }

    private void carregarDados(List<Cliente> clientes) {
       
        clientes.forEach(c -> {
            tableModel.addRow(new Object[] {
                c.getId(),
                c.getNome(),
                c.getTelefone(),
                c.getEmail()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbClientes);

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSelecionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        linhaSelecionada = tbClientes.getSelectedRow();
        
        if(linhaSelecionada >= 0){
            Cliente cliente = new Cliente();
            
            cliente.setId((Integer) tbClientes.getValueAt(linhaSelecionada, 0));
            cliente.setNome((String) tbClientes.getValueAt(linhaSelecionada, 1));
            cliente.setEmail((String) tbClientes.getValueAt(linhaSelecionada, 3));
            cliente.setTelefone((String) tbClientes.getValueAt(linhaSelecionada, 2));
            
            linhaSelecionada = -1;
            viewLancarVenda.preencherDadosCliente(cliente);
            dispose();
            
        }else {
            
            JOptionPane.showMessageDialog(this, 
                    "Selecione um cliente da listagem.", 
                    "Atenção", 
                    JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_btSelecionarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    // End of variables declaration//GEN-END:variables

   
    
    
}
